### ISSUE TITLE
Error in logging???

### ISSUE THREAD

**Issue by wanghaEMQ** [emqx/nanomq#1132]
**Describe the bug**

```
==7391==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x000103052cf1 at pc 0x0001007b8088 bp 0x00017062d210 sp 0x00017062c9d0
READ of size 2 at 0x000103052cf1 thread T15
2023-04-03 17:38:48 [7391] TRACE /Users/wangha/Documents/Git/nanomq/nng/src/sp/transport/mqtt/broker_tcp.c:603  tcptran_pipe_recv_cb: tcptran_pipe_recv_cb 0x104207ac0

    #0 0x1007b8084 in wrap_strlen+0x164 (libclang_rt.asan_osx_dynamic.dylib:arm64e+0x18084) (BuildId: 112043985f03370ebc205328b62c210a32000000200000000100000000000b00)
    #1 0x186443b8c in vsscanf_l+0xa0 (libsystem_c.dylib:arm64e+0xab8c) (BuildId: 14cd841b0c7b34a2a342cc6796ef925932000000200000000100000000020d00)
    #2 0x1007c0778 in wrap_sscanf+0x7c (libclang_rt.asan_osx_dynamic.dylib:arm64e+0x20778) (BuildId: 112043985f03370ebc205328b62c210a32000000200000000100000000000b00)
    #3 0x1002619e8 in file_rotation log.c:208
    #4 0x10026021c in file_callback log.c:88
    #5 0x1002610d0 in log_log log.c:288
    #6 0x100112c4c in nano_pipe_recv_cb nmq_mqtt.c:994
    #7 0x1000a33f8 in nni_task_exec taskq.c:144
    #8 0x10006f4b8 in nni_aio_finish_impl aio.c:454
    #9 0x10006f50c in nni_aio_finish_sync aio.c:469
    #10 0x10014d01c in tcptran_pipe_recv_cb broker_tcp.c:844
    #11 0x1000a2cbc in nni_taskq_thread taskq.c:50
    #12 0x1000a777c in nni_thr_wrap thread.c:94
    #13 0x1000c9378 in nni_plat_thr_main posix_thread.c:266
    #14 0x18657a068 in _pthread_start+0x90 (libsystem_pthread.dylib:arm64e+0x7068) (BuildId: 9f3b729aed043e65adacd75ad06ebbdc32000000200000000100000000020d00)
    #15 0x186574e28 in thread_start+0x4 (libsystem_pthread.dylib:arm64e+0x1e28) (BuildId: 9f3b729aed043e65adacd75ad06ebbdc32000000200000000100000000020d00)

0x000103052cf1 is located 0 bytes to the right of 1-byte region [0x000103052cf0,0x000103052cf1)
allocated by thread T15 here:
    #0 0x1007e2e68 in wrap_malloc+0x94 (libclang_rt.asan_osx_dynamic.dylib:arm64e+0x42e68) (BuildId: 112043985f03370ebc205328b62c210a32000000200000000100000000000b00)
    #1 0x1000ae1b0 in nni_alloc posix_alloc.c:20
    #2 0x1000b0724 in nni_plat_file_get posix_file.c:119
    #3 0x100261980 in file_rotation log.c:206
    #4 0x10026021c in file_callback log.c:88
    #5 0x1002610d0 in log_log log.c:288
    #6 0x100112c4c in nano_pipe_recv_cb nmq_mqtt.c:994
    #7 0x1000a33f8 in nni_task_exec taskq.c:144
    #8 0x10006f4b8 in nni_aio_finish_impl aio.c:454
    #9 0x10006f50c in nni_aio_finish_sync aio.c:469
    #10 0x10014d01c in tcptran_pipe_recv_cb broker_tcp.c:844
    #11 0x1000a2cbc in nni_taskq_thread taskq.c:50
    #12 0x1000a777c in nni_thr_wrap thread.c:94
    #13 0x1000c9378 in nni_plat_thr_main posix_thread.c:266
    #14 0x18657a068 in _pthread_start+0x90 (libsystem_pthread.dylib:arm64e+0x7068) (BuildId: 9f3b729aed043e65adacd75ad06ebbdc32000000200000000100000000020d00)
    #15 0x186574e28 in thread_start+0x4 (libsystem_pthread.dylib:arm64e+0x1e28) (BuildId: 9f3b729aed043e65adacd75ad06ebbdc32000000200000000100000000020d00)

Thread T15 created by T0 here:
    #0 0x1007dcd2c in wrap_pthread_create+0x54 (libclang_rt.asan_osx_dynamic.dylib:arm64e+0x3cd2c) (BuildId: 112043985f03370ebc205328b62c210a32000000200000000100000000000b00)
    #1 0x1000c905c in nni_plat_thr_init posix_thread.c:279
    #2 0x1000a73f4 in nni_thr_init thread.c:121
    #3 0x1000a2924 in nni_taskq_init taskq.c:95
    #4 0x1000a413c in nni_taskq_sys_init taskq.c:294
    #5 0x10007a81c in nni_init_helper init.c:35
    #6 0x1000c9840 in nni_plat_init posix_thread.c:422
    #7 0x10007a804 in nni_init init.c:58
    #8 0x100182f94 in nng_mtx_alloc platform.c:93
    #9 0x100003bb0 in log_init mqtt_api.c:223
    #10 0x10004b198 in broker_start broker.c:1592
    #11 0x1000045fc in main nanomq.c:142
    #12 0x18624fe4c  (<unknown module>)

SUMMARY: AddressSanitizer: heap-buffer-overflow (libclang_rt.asan_osx_dynamic.dylib:arm64e+0x18084) (BuildId: 112043985f03370ebc205328b62c210a32000000200000000100000000000b00) in wrap_strlen+0x164
Shadow bytes around the buggy address:
  0x00702062a540: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x00702062a550: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x00702062a560: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x00702062a570: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x00702062a580: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x00702062a590: fa fa fa fa fa fa fa fa fa fa fa fa fa fa[01]fa
  0x00702062a5a0: fa fa 00 03 fa fa fd fa fa fa fa fa fa fa fa fa
  0x00702062a5b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x00702062a5c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x00702062a5d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x00702062a5e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb

```

**Expected behavior**
logger works.

**Actual Behavior**
Errors happened in logger.

**To Reproduce**

** Environment Details **
 - NanoMQ version
 - Operating system and version
 - Compiler and language used
 - testing scenario

**Client SDK**

**Additional context**

**Comment by wanghaEMQ** [comment]
The PR https://github.com/nanomq/NanoNNG/pull/489 has fixed it
