### ISSUE TITLE
Memory leakages in nanomq_cli bench tool

### ISSUE THREAD

**Issue by wanghaEMQ** [emqx/nanomq#1346]
**Describe the bug**

```
==44220==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 409600 byte(s) in 200 object(s) allocated from:
    #0 0xffff8064e500 in malloc (/lib64/libasan.so.8+0xae500)
    #1 0x4abd74 in nni_alloc /root/nanomq/nng/src/platform/posix/posix_alloc.c:20
    #2 0x477818 in nng_alloc /root/nanomq/nng/src/nng.c:60
    #3 0x452658 in pub_cb /root/nanomq/nanomq_cli/bench.c:216
    #4 0x454db4 in nnb_publish /root/nanomq/nanomq_cli/bench.c:526
    #5 0x45501c in bench_start /root/nanomq/nanomq_cli/bench.c:558
    #6 0x45e35c in main /root/nanomq/nanomq_cli/main.c:106
    #7 0xffff800973c4 in __libc_start_call_main (/lib64/libc.so.6+0x273c4)
    #8 0xffff8009749c in __libc_start_main_alias_2 (/lib64/libc.so.6+0x2749c)
    #9 0x45126c in _start (/root/nanomq/build/nanomq_cli/nanomq_cli+0x45126c)

SUMMARY: AddressSanitizer: 409600 byte(s) leaked in 200 allocation(s).
```

**To Reproduce**

Run `./nanomq_cli/nanomq_cli bench pub -h 127.0.0.1 -p 1883 -q 2 -t topic1/a -s 2048`
Then stopping mqtt broker.
The `nanomq_cli bench` tool was stopped because there were no active connections.
Then memory leakage happened.

**Environment Details**
 - NanoMQ version
 - Operating system and version
 - Compiler and language used
 - testing scenario

**Client SDK**

**Additional context**

**Comment by OdyWayne** [comment]
I think the leak is no longer exist, just tested it.
