### ISSUE TITLE
Memory leak in nanomq.

### ISSUE THREAD

**Issue by wanghaEMQ** [emqx/nanomq#1378]
**Describe the bug**
```
=================================================================
==65495==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 848 byte(s) in 1 object(s) allocated from:
    #0 0xffff9388e500 in malloc (/lib64/libasan.so.8+0xae500)
    #1 0xffff9356f794 in CxPlatAlloc /root/nanomq/nng/extern/msquic/src/platform/platform_posix.c:263
    #2 0xffff9356d7a0 in CxPlatPoolAlloc /root/nanomq/nng/extern/msquic/src/inc/quic_platform_posix.h:531
    #3 0xffff934fa914 in QuicStreamInitialize /root/nanomq/nng/extern/msquic/src/core/stream.c:35
    #4 0xffff93511fe4 in MsQuicStreamOpen /root/nanomq/nng/extern/msquic/src/core/api.c:661
    #5 0x5a6d6c in quic_pipe_open /root/nanomq/nng/src/supplemental/quic/quic_api.c:1398
    #6 0x4e8b4c in quic_mqtt_stream_init /root/nanomq/nng/src/mqtt/protocol/mqtt/mqttv5_quic.c:1465
    #7 0x5a1f38 in quic_connection_cb /root/nanomq/nng/src/supplemental/quic/quic_api.c:595
    #8 0xffff9351cd00 in QuicConnIndicateEvent /root/nanomq/nng/extern/msquic/src/core/connection.c:749
    #9 0xffff935376dc in QuicCryptoProcessTlsCompletion /root/nanomq/nng/extern/msquic/src/core/crypto.c:1643
    #10 0xffff9353860c in QuicCryptoProcessDataComplete /root/nanomq/nng/extern/msquic/src/core/crypto.c:1691
    #11 0xffff93538848 in QuicCryptoProcessData /root/nanomq/nng/extern/msquic/src/core/crypto.c:1845
    #12 0xffff935398e8 in QuicCryptoProcessFrame /root/nanomq/nng/extern/msquic/src/core/crypto.c:1319
    #13 0xffff93529d78 in QuicConnRecvFrames /root/nanomq/nng/extern/msquic/src/core/connection.c:4528
    #14 0xffff9352c5ec in QuicConnRecvDatagramBatch /root/nanomq/nng/extern/msquic/src/core/connection.c:5454
    #15 0xffff9352d7b4 in QuicConnRecvDatagrams /root/nanomq/nng/extern/msquic/src/core/connection.c:5633
    #16 0xffff9352e160 in QuicConnFlushRecv /root/nanomq/nng/extern/msquic/src/core/connection.c:5784
    #17 0xffff93532df4 in QuicConnDrainOperations /root/nanomq/nng/extern/msquic/src/core/connection.c:7442
    #18 0xffff935089e8 in QuicWorkerProcessConnection /root/nanomq/nng/extern/msquic/src/core/worker.c:510
    #19 0xffff93509004 in QuicWorkerLoop /root/nanomq/nng/extern/msquic/src/core/worker.c:667
    #20 0xffff9356b0c4 in CxPlatRunExecutionContexts /root/nanomq/nng/extern/msquic/src/platform/platform_worker.c:369
    #21 0xffff9356b834 in CxPlatWorkerThread /root/nanomq/nng/extern/msquic/src/platform/platform_worker.c:454
    #22 0xffff933309a4 in start_thread (/lib64/libc.so.6+0x809a4)
    #23 0xffff9339bd18 in thread_start (/lib64/libc.so.6+0xebd18)

Indirect leak of 4096 byte(s) in 1 object(s) allocated from:
    #0 0xffff9388e500 in malloc (/lib64/libasan.so.8+0xae500)
    #1 0xffff9356f794 in CxPlatAlloc /root/nanomq/nng/extern/msquic/src/platform/platform_posix.c:263
    #2 0xffff9356d7a0 in CxPlatPoolAlloc /root/nanomq/nng/extern/msquic/src/inc/quic_platform_posix.h:531
    #3 0xffff934faeec in QuicStreamInitialize /root/nanomq/nng/extern/msquic/src/core/stream.c:104
    #4 0xffff93511fe4 in MsQuicStreamOpen /root/nanomq/nng/extern/msquic/src/core/api.c:661
    #5 0x5a6d6c in quic_pipe_open /root/nanomq/nng/src/supplemental/quic/quic_api.c:1398
    #6 0x4e8b4c in quic_mqtt_stream_init /root/nanomq/nng/src/mqtt/protocol/mqtt/mqttv5_quic.c:1465
    #7 0x5a1f38 in quic_connection_cb /root/nanomq/nng/src/supplemental/quic/quic_api.c:595
    #8 0xffff9351cd00 in QuicConnIndicateEvent /root/nanomq/nng/extern/msquic/src/core/connection.c:749
    #9 0xffff935376dc in QuicCryptoProcessTlsCompletion /root/nanomq/nng/extern/msquic/src/core/crypto.c:1643
    #10 0xffff9353860c in QuicCryptoProcessDataComplete /root/nanomq/nng/extern/msquic/src/core/crypto.c:1691
    #11 0xffff93538848 in QuicCryptoProcessData /root/nanomq/nng/extern/msquic/src/core/crypto.c:1845
    #12 0xffff935398e8 in QuicCryptoProcessFrame /root/nanomq/nng/extern/msquic/src/core/crypto.c:1319
    #13 0xffff93529d78 in QuicConnRecvFrames /root/nanomq/nng/extern/msquic/src/core/connection.c:4528
    #14 0xffff9352c5ec in QuicConnRecvDatagramBatch /root/nanomq/nng/extern/msquic/src/core/connection.c:5454
    #15 0xffff9352d7b4 in QuicConnRecvDatagrams /root/nanomq/nng/extern/msquic/src/core/connection.c:5633
    #16 0xffff9352e160 in QuicConnFlushRecv /root/nanomq/nng/extern/msquic/src/core/connection.c:5784
    #17 0xffff93532df4 in QuicConnDrainOperations /root/nanomq/nng/extern/msquic/src/core/connection.c:7442
    #18 0xffff935089e8 in QuicWorkerProcessConnection /root/nanomq/nng/extern/msquic/src/core/worker.c:510
    #19 0xffff93509004 in QuicWorkerLoop /root/nanomq/nng/extern/msquic/src/core/worker.c:667
    #20 0xffff9356b0c4 in CxPlatRunExecutionContexts /root/nanomq/nng/extern/msquic/src/platform/platform_worker.c:369
    #21 0xffff9356b834 in CxPlatWorkerThread /root/nanomq/nng/extern/msquic/src/platform/platform_worker.c:454
    #22 0xffff933309a4 in start_thread (/lib64/libc.so.6+0x809a4)
    #23 0xffff9339bd18 in thread_start (/lib64/libc.so.6+0xebd18)

Indirect leak of 784 byte(s) in 1 object(s) allocated from:
    #0 0xffff9388e500 in malloc (/lib64/libasan.so.8+0xae500)
    #1 0x4cd0d8 in nni_alloc /root/nanomq/nng/src/platform/posix/posix_alloc.c:20
    #2 0x498b7c in nng_alloc /root/nanomq/nng/src/nng.c:60
    #3 0x5a6cc0 in quic_pipe_open /root/nanomq/nng/src/supplemental/quic/quic_api.c:1389
    #4 0x4e8b4c in quic_mqtt_stream_init /root/nanomq/nng/src/mqtt/protocol/mqtt/mqttv5_quic.c:1465
    #5 0x5a1f38 in quic_connection_cb /root/nanomq/nng/src/supplemental/quic/quic_api.c:595
    #6 0xffff9351cd00 in QuicConnIndicateEvent /root/nanomq/nng/extern/msquic/src/core/connection.c:749
    #7 0xffff935376dc in QuicCryptoProcessTlsCompletion /root/nanomq/nng/extern/msquic/src/core/crypto.c:1643
    #8 0xffff9353860c in QuicCryptoProcessDataComplete /root/nanomq/nng/extern/msquic/src/core/crypto.c:1691
    #9 0xffff93538848 in QuicCryptoProcessData /root/nanomq/nng/extern/msquic/src/core/crypto.c:1845
    #10 0xffff935398e8 in QuicCryptoProcessFrame /root/nanomq/nng/extern/msquic/src/core/crypto.c:1319
    #11 0xffff93529d78 in QuicConnRecvFrames /root/nanomq/nng/extern/msquic/src/core/connection.c:4528
    #12 0xffff9352c5ec in QuicConnRecvDatagramBatch /root/nanomq/nng/extern/msquic/src/core/connection.c:5454
    #13 0xffff9352d7b4 in QuicConnRecvDatagrams /root/nanomq/nng/extern/msquic/src/core/connection.c:5633
    #14 0xffff9352e160 in QuicConnFlushRecv /root/nanomq/nng/extern/msquic/src/core/connection.c:5784
    #15 0xffff93532df4 in QuicConnDrainOperations /root/nanomq/nng/extern/msquic/src/core/connection.c:7442
    #16 0xffff935089e8 in QuicWorkerProcessConnection /root/nanomq/nng/extern/msquic/src/core/worker.c:510
    #17 0xffff93509004 in QuicWorkerLoop /root/nanomq/nng/extern/msquic/src/core/worker.c:667
    #18 0xffff9356b0c4 in CxPlatRunExecutionContexts /root/nanomq/nng/extern/msquic/src/platform/platform_worker.c:369
    #19 0xffff9356b834 in CxPlatWorkerThread /root/nanomq/nng/extern/msquic/src/platform/platform_worker.c:454
    #20 0xffff933309a4 in start_thread (/lib64/libc.so.6+0x809a4)
    #21 0xffff9339bd18 in thread_start (/lib64/libc.so.6+0xebd18)

Indirect leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0xffff9388e500 in malloc (/lib64/libasan.so.8+0xae500)
    #1 0x4cd0d8 in nni_alloc /root/nanomq/nng/src/platform/posix/posix_alloc.c:20
    #2 0x4b3d0c in nni_lmq_resize /root/nanomq/nng/src/core/lmq.c:132
    #3 0x4b344c in nni_lmq_init /root/nanomq/nng/src/core/lmq.c:33
    #4 0x5a03e8 in quic_strm_init /root/nanomq/nng/src/supplemental/quic/quic_api.c:355
    #5 0x5a6ce4 in quic_pipe_open /root/nanomq/nng/src/supplemental/quic/quic_api.c:1392
    #6 0x4e8b4c in quic_mqtt_stream_init /root/nanomq/nng/src/mqtt/protocol/mqtt/mqttv5_quic.c:1465
    #7 0x5a1f38 in quic_connection_cb /root/nanomq/nng/src/supplemental/quic/quic_api.c:595
    #8 0xffff9351cd00 in QuicConnIndicateEvent /root/nanomq/nng/extern/msquic/src/core/connection.c:749
    #9 0xffff935376dc in QuicCryptoProcessTlsCompletion /root/nanomq/nng/extern/msquic/src/core/crypto.c:1643
    #10 0xffff9353860c in QuicCryptoProcessDataComplete /root/nanomq/nng/extern/msquic/src/core/crypto.c:1691
    #11 0xffff93538848 in QuicCryptoProcessData /root/nanomq/nng/extern/msquic/src/core/crypto.c:1845
    #12 0xffff935398e8 in QuicCryptoProcessFrame /root/nanomq/nng/extern/msquic/src/core/crypto.c:1319
    #13 0xffff93529d78 in QuicConnRecvFrames /root/nanomq/nng/extern/msquic/src/core/connection.c:4528
    #14 0xffff9352c5ec in QuicConnRecvDatagramBatch /root/nanomq/nng/extern/msquic/src/core/connection.c:5454
    #15 0xffff9352d7b4 in QuicConnRecvDatagrams /root/nanomq/nng/extern/msquic/src/core/connection.c:5633
    #16 0xffff9352e160 in QuicConnFlushRecv /root/nanomq/nng/extern/msquic/src/core/connection.c:5784
    #17 0xffff93532df4 in QuicConnDrainOperations /root/nanomq/nng/extern/msquic/src/core/connection.c:7442
    #18 0xffff935089e8 in QuicWorkerProcessConnection /root/nanomq/nng/extern/msquic/src/core/worker.c:510
    #19 0xffff93509004 in QuicWorkerLoop /root/nanomq/nng/extern/msquic/src/core/worker.c:667
    #20 0xffff9356b0c4 in CxPlatRunExecutionContexts /root/nanomq/nng/extern/msquic/src/platform/platform_worker.c:369
    #21 0xffff9356b834 in CxPlatWorkerThread /root/nanomq/nng/extern/msquic/src/platform/platform_worker.c:454
    #22 0xffff933309a4 in start_thread (/lib64/libc.so.6+0x809a4)
    #23 0xffff9339bd18 in thread_start (/lib64/libc.so.6+0xebd18)

Indirect leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0xffff9388e500 in malloc (/lib64/libasan.so.8+0xae500)
    #1 0x4cd0d8 in nni_alloc /root/nanomq/nng/src/platform/posix/posix_alloc.c:20
    #2 0x4b3d0c in nni_lmq_resize /root/nanomq/nng/src/core/lmq.c:132
    #3 0x4b344c in nni_lmq_init /root/nanomq/nng/src/core/lmq.c:33
    #4 0x5a03f8 in quic_strm_init /root/nanomq/nng/src/supplemental/quic/quic_api.c:356
    #5 0x5a6ce4 in quic_pipe_open /root/nanomq/nng/src/supplemental/quic/quic_api.c:1392
    #6 0x4e8b4c in quic_mqtt_stream_init /root/nanomq/nng/src/mqtt/protocol/mqtt/mqttv5_quic.c:1465
    #7 0x5a1f38 in quic_connection_cb /root/nanomq/nng/src/supplemental/quic/quic_api.c:595
    #8 0xffff9351cd00 in QuicConnIndicateEvent /root/nanomq/nng/extern/msquic/src/core/connection.c:749
    #9 0xffff935376dc in QuicCryptoProcessTlsCompletion /root/nanomq/nng/extern/msquic/src/core/crypto.c:1643
    #10 0xffff9353860c in QuicCryptoProcessDataComplete /root/nanomq/nng/extern/msquic/src/core/crypto.c:1691
    #11 0xffff93538848 in QuicCryptoProcessData /root/nanomq/nng/extern/msquic/src/core/crypto.c:1845
    #12 0xffff935398e8 in QuicCryptoProcessFrame /root/nanomq/nng/extern/msquic/src/core/crypto.c:1319
    #13 0xffff93529d78 in QuicConnRecvFrames /root/nanomq/nng/extern/msquic/src/core/connection.c:4528
    #14 0xffff9352c5ec in QuicConnRecvDatagramBatch /root/nanomq/nng/extern/msquic/src/core/connection.c:5454
    #15 0xffff9352d7b4 in QuicConnRecvDatagrams /root/nanomq/nng/extern/msquic/src/core/connection.c:5633
    #16 0xffff9352e160 in QuicConnFlushRecv /root/nanomq/nng/extern/msquic/src/core/connection.c:5784
    #17 0xffff93532df4 in QuicConnDrainOperations /root/nanomq/nng/extern/msquic/src/core/connection.c:7442
    #18 0xffff935089e8 in QuicWorkerProcessConnection /root/nanomq/nng/extern/msquic/src/core/worker.c:510
    #19 0xffff93509004 in QuicWorkerLoop /root/nanomq/nng/extern/msquic/src/core/worker.c:667
    #20 0xffff9356b0c4 in CxPlatRunExecutionContexts /root/nanomq/nng/extern/msquic/src/platform/platform_worker.c:369
    #21 0xffff9356b834 in CxPlatWorkerThread /root/nanomq/nng/extern/msquic/src/platform/platform_worker.c:454
    #22 0xffff933309a4 in start_thread (/lib64/libc.so.6+0x809a4)
    #23 0xffff9339bd18 in thread_start (/lib64/libc.so.6+0xebd18)

Indirect leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0xffff9388e500 in malloc (/lib64/libasan.so.8+0xae500)
    #1 0xffff9356f794 in CxPlatAlloc /root/nanomq/nng/extern/msquic/src/platform/platform_posix.c:263
    #2 0xffff9356d7a0 in CxPlatPoolAlloc /root/nanomq/nng/extern/msquic/src/inc/quic_platform_posix.h:531
    #3 0xffff9354e71c in QuicOperationAlloc /root/nanomq/nng/extern/msquic/src/core/operation.c:69
    #4 0xffff93513334 in MsQuicStreamReceiveSetEnabled /root/nanomq/nng/extern/msquic/src/core/api.c:1187
    #5 0x5a4c20 in quic_pipe_recv_start /root/nanomq/nng/src/supplemental/quic/quic_api.c:1061
    #6 0x5a6a3c in quic_pipe_recv /root/nanomq/nng/src/supplemental/quic/quic_api.c:1344
    #7 0x4e95b8 in quic_mqtt_stream_start /root/nanomq/nng/src/mqtt/protocol/mqtt/mqttv5_quic.c:1596
    #8 0x5a1f94 in quic_connection_cb /root/nanomq/nng/src/supplemental/quic/quic_api.c:598
    #9 0xffff9351cd00 in QuicConnIndicateEvent /root/nanomq/nng/extern/msquic/src/core/connection.c:749
    #10 0xffff935376dc in QuicCryptoProcessTlsCompletion /root/nanomq/nng/extern/msquic/src/core/crypto.c:1643
    #11 0xffff9353860c in QuicCryptoProcessDataComplete /root/nanomq/nng/extern/msquic/src/core/crypto.c:1691
    #12 0xffff93538848 in QuicCryptoProcessData /root/nanomq/nng/extern/msquic/src/core/crypto.c:1845
    #13 0xffff935398e8 in QuicCryptoProcessFrame /root/nanomq/nng/extern/msquic/src/core/crypto.c:1319
    #14 0xffff93529d78 in QuicConnRecvFrames /root/nanomq/nng/extern/msquic/src/core/connection.c:4528
    #15 0xffff9352c5ec in QuicConnRecvDatagramBatch /root/nanomq/nng/extern/msquic/src/core/connection.c:5454
    #16 0xffff9352d7b4 in QuicConnRecvDatagrams /root/nanomq/nng/extern/msquic/src/core/connection.c:5633
    #17 0xffff9352e160 in QuicConnFlushRecv /root/nanomq/nng/extern/msquic/src/core/connection.c:5784
    #18 0xffff93532df4 in QuicConnDrainOperations /root/nanomq/nng/extern/msquic/src/core/connection.c:7442
    #19 0xffff935089e8 in QuicWorkerProcessConnection /root/nanomq/nng/extern/msquic/src/core/worker.c:510
    #20 0xffff93509004 in QuicWorkerLoop /root/nanomq/nng/extern/msquic/src/core/worker.c:667
    #21 0xffff9356b0c4 in CxPlatRunExecutionContexts /root/nanomq/nng/extern/msquic/src/platform/platform_worker.c:369
    #22 0xffff9356b834 in CxPlatWorkerThread /root/nanomq/nng/extern/msquic/src/platform/platform_worker.c:454
    #23 0xffff933309a4 in start_thread (/lib64/libc.so.6+0x809a4)
    #24 0xffff9339bd18 in thread_start (/lib64/libc.so.6+0xebd18)

Indirect leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0xffff9388e500 in malloc (/lib64/libasan.so.8+0xae500)
    #1 0xffff9356f794 in CxPlatAlloc /root/nanomq/nng/extern/msquic/src/platform/platform_posix.c:263
    #2 0xffff9356d7a0 in CxPlatPoolAlloc /root/nanomq/nng/extern/msquic/src/inc/quic_platform_posix.h:531
    #3 0xffff9354e684 in QuicOperationAlloc /root/nanomq/nng/extern/msquic/src/core/operation.c:59
    #4 0xffff93513334 in MsQuicStreamReceiveSetEnabled /root/nanomq/nng/extern/msquic/src/core/api.c:1187
    #5 0x5a4c20 in quic_pipe_recv_start /root/nanomq/nng/src/supplemental/quic/quic_api.c:1061
    #6 0x5a6a3c in quic_pipe_recv /root/nanomq/nng/src/supplemental/quic/quic_api.c:1344
    #7 0x4e95b8 in quic_mqtt_stream_start /root/nanomq/nng/src/mqtt/protocol/mqtt/mqttv5_quic.c:1596
    #8 0x5a1f94 in quic_connection_cb /root/nanomq/nng/src/supplemental/quic/quic_api.c:598
    #9 0xffff9351cd00 in QuicConnIndicateEvent /root/nanomq/nng/extern/msquic/src/core/connection.c:749
    #10 0xffff935376dc in QuicCryptoProcessTlsCompletion /root/nanomq/nng/extern/msquic/src/core/crypto.c:1643
    #11 0xffff9353860c in QuicCryptoProcessDataComplete /root/nanomq/nng/extern/msquic/src/core/crypto.c:1691
    #12 0xffff93538848 in QuicCryptoProcessData /root/nanomq/nng/extern/msquic/src/core/crypto.c:1845
    #13 0xffff935398e8 in QuicCryptoProcessFrame /root/nanomq/nng/extern/msquic/src/core/crypto.c:1319
    #14 0xffff93529d78 in QuicConnRecvFrames /root/nanomq/nng/extern/msquic/src/core/connection.c:4528
    #15 0xffff9352c5ec in QuicConnRecvDatagramBatch /root/nanomq/nng/extern/msquic/src/core/connection.c:5454
    #16 0xffff9352d7b4 in QuicConnRecvDatagrams /root/nanomq/nng/extern/msquic/src/core/connection.c:5633
    #17 0xffff9352e160 in QuicConnFlushRecv /root/nanomq/nng/extern/msquic/src/core/connection.c:5784
    #18 0xffff93532df4 in QuicConnDrainOperations /root/nanomq/nng/extern/msquic/src/core/connection.c:7442
    #19 0xffff935089e8 in QuicWorkerProcessConnection /root/nanomq/nng/extern/msquic/src/core/worker.c:510
    #20 0xffff93509004 in QuicWorkerLoop /root/nanomq/nng/extern/msquic/src/core/worker.c:667
    #21 0xffff9356b0c4 in CxPlatRunExecutionContexts /root/nanomq/nng/extern/msquic/src/platform/platform_worker.c:369
    #22 0xffff9356b834 in CxPlatWorkerThread /root/nanomq/nng/extern/msquic/src/platform/platform_worker.c:454
    #23 0xffff933309a4 in start_thread (/lib64/libc.so.6+0x809a4)
    #24 0xffff9339bd18 in thread_start (/lib64/libc.so.6+0xebd18)

Indirect leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0xffff9388d538 in __interceptor_realloc.part.0 (/lib64/libasan.so.8+0xad538)
    #1 0x5a0fe8 in quic_strm_cb /root/nanomq/nng/src/supplemental/quic/quic_api.c:472
    #2 0xffff934fb664 in QuicStreamIndicateEvent /root/nanomq/nng/extern/msquic/src/core/stream.c:438
    #3 0xffff934feac8 in QuicStreamRecvFlush /root/nanomq/nng/extern/msquic/src/core/stream_recv.c:867
    #4 0xffff93532e2c in QuicConnDrainOperations /root/nanomq/nng/extern/msquic/src/core/connection.c:7459
    #5 0xffff935089e8 in QuicWorkerProcessConnection /root/nanomq/nng/extern/msquic/src/core/worker.c:510
    #6 0xffff93509004 in QuicWorkerLoop /root/nanomq/nng/extern/msquic/src/core/worker.c:667
    #7 0xffff9356b0c4 in CxPlatRunExecutionContexts /root/nanomq/nng/extern/msquic/src/platform/platform_worker.c:369
    #8 0xffff9356b834 in CxPlatWorkerThread /root/nanomq/nng/extern/msquic/src/platform/platform_worker.c:454
    #9 0xffff933309a4 in start_thread (/lib64/libc.so.6+0x809a4)
    #10 0xffff9339bd18 in thread_start (/lib64/libc.so.6+0xebd18)

SUMMARY: AddressSanitizer: 6144 byte(s) leaked in 8 allocation(s).
```

**Expected behavior**
No memory leakages.

**To Reproduce**

```
Start quic bridge.
Add subscription for bridge.

curl --location 'http://127.0.0.1:8081/api/v4/bridges/sub/emqx' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic YWRtaW46cHVibGlj' \
--data '{
    "data": {
        "subscription": [
            {
                "topic": "test",
                "qos": 0
            },
            {
                "topic": "cmd/topic5",
                "qos": 2
            }
        ],
        "sub_properties": {
            "identifier": 1,
            "user_properties": [
                {
                    "key": "key1",
                    "value": "value1"
                },
                {
                    "key": "key2",
                    "value": "value2"
                }
            ]
        }
    }
}
'

Unsubcribe those topic.
curl --location 'http://127.0.0.1:8081/api/v4/bridges/unsub/emqx' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic YWRtaW46cHVibGlj' \
--data '{
    "data": {
        "unsubscription": [
            {
                "topic": "test"
            },
            {
                "topic": "cmd/topic2"
            }
        ],
        "unsub_properties": {
            "user_properties": [
                {
                    "key": "key1",
                    "value": "value1"
                },
                {
                    "key": "key2",
                    "value": "value2"
                }
            ]
        }
    }
}
'
```

** Environment Details **
 - NanoMQ version. Latest
 - Operating system and version
 - Compiler and language used
 - testing scenario

**Client SDK**
If possible include the mqtt sdk you used to connect to nanomq
Minimal C test cases are perferred.

**Additional context**

**Comment by JaylinYu** [comment]
QUIC part doesnt support dynamic bridge yet

**Comment by JaylinYu** [comment]
is this already fixed?

**Comment by wanghaEMQ** [comment]
Yes. It has been fixed.
