### ISSUE TITLE
error of msg_ret

### ISSUE THREAD

**Issue by wanghaEMQ** [emqx/nanomq#401]
log from asan

```
==101009==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x55c7fb45b936 bp 0x7efe0aff6d10 sp 0x7efe0aff6b90 T9)
==101009==The signal is caused by a READ memory access.
==101009==Hint: address points to the zero page.
    #0 0x55c7fb45b935 in server_cb ../nanomq/apps/broker.c:361
    #1 0x55c7fb495969 in nni_taskq_thread ../nng/src/core/taskq.c:50
    #2 0x55c7fb496bd8 in nni_thr_wrap ../nng/src/core/thread.c:94
    #3 0x55c7fb49f3d2 in nni_plat_thr_main ../nng/src/platform/posix/posix_thread.c:266
    #4 0x7efe1276d608 in start_thread /build/glibc-sMfBJT/glibc-2.31/nptl/pthread_create.c:477
    #5 0x7efe12661162 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x11f162)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ../nanomq/apps/broker.c:361 in server_cb
Thread T9 (nng:task) created by T0 here:
    #0 0x7efe127c2815 in __interceptor_pthread_create ../../../../src/libsanitizer/asan/asan_interceptors.cc:208
    #1 0x55c7fb49f502 in nni_plat_thr_init ../nng/src/platform/posix/posix_thread.c:279
    #2 0x55c7fb496e81 in nni_thr_init ../nng/src/core/thread.c:121
    #3 0x55c7fb495c8a in nni_taskq_init ../nng/src/core/taskq.c:95
    #4 0x55c7fb4968a8 in nni_taskq_sys_init ../nng/src/core/taskq.c:284
    #5 0x55c7fb481fca in nni_init_helper ../nng/src/core/init.c:35
    #6 0x55c7fb49f856 in nni_plat_init ../nng/src/platform/posix/posix_thread.c:422
    #7 0x55c7fb482048 in nni_init ../nng/src/core/init.c:58
    #8 0x55c7fb4b66da in nni_proto_mqtt_open ../nng/src/sp/protocol.c:37
    #9 0x55c7fb4b643d in nng_nmq_tcp0_open ../nng/src/sp/protocol/mqtt/nmq_mqtt.c:1173
    #10 0x55c7fb45eab2 in broker ../nanomq/apps/broker.c:723
    #11 0x55c7fb4613a3 in broker_start ../nanomq/apps/broker.c:1154
    #12 0x55c7fb43d355 in main ../nanomq/nanomq.c:187
    #13 0x7efe125660b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x240b2)
```

## How to reproduce

Cause by fuzzing...

**Comment by JaylinYu** [comment]
can you reproduce it in 0.7.1?
