### ISSUE TITLE
Retain As Published test caused abort.

### ISSUE THREAD

**Issue by lee-emqx** [emqx/nanomq#601]
Launched nanomq by `./nanomq/nanomq broker start`,
Run [nnc_test_v5.py](https://github.com/nanomq/nanomq-ci/blob/main/nnc_test_v5.py)
Caused nanomq abort.
```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==30416==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000038 (pc 0x000100f95bce bp 0x70000228de30 sp 0x70000228dc90 T13)
==30416==The signal is caused by a READ memory access.
==30416==Hint: address points to the zero page.
    #0 0x100f95bce in property_dup mqtt_codec.c:2278
    #1 0x100e017cd in handle_pub_retain pub_handler.c:409
    #2 0x100dffc5d in handle_pub pub_handler.c:381
    #3 0x100e23d1d in server_cb broker.c:211
    #4 0x100eaebbe in nni_task_exec taskq.c:144
    #5 0x100e7f3a4 in nni_aio_finish_impl aio.c:448
    #6 0x100e7f3fc in nni_aio_finish_sync aio.c:463
    #7 0x100f19bad in nano_pipe_recv_cb nmq_mqtt.c:1079
    #8 0x100eaebbe in nni_task_exec taskq.c:144
    #9 0x100e7f3a4 in nni_aio_finish_impl aio.c:448
    #10 0x100e7f3fc in nni_aio_finish_sync aio.c:463
    #11 0x100f42bc1 in tcptran_pipe_recv_cb broker_tcp.c:749
    #12 0x100eae4ff in nni_taskq_thread taskq.c:50
    #13 0x100eb2897 in nni_thr_wrap thread.c:94
    #14 0x100ed18bc in nni_plat_thr_main posix_thread.c:266
    #15 0x7fff6b485108 in _pthread_start+0x93 (libsystem_pthread.dylib:x86_64+0x6108)
    #16 0x7fff6b480b8a in thread_start+0xe (libsystem_pthread.dylib:x86_64+0x1b8a)

==30416==Register values:
rax = 0x0000000000000038  rbx = 0x000070000228de80  rcx = 0x0000100000000007  rdx = 0x0000100000000000  
rdi = 0x00006060000232c0  rsi = 0x0000000000000000  rbp = 0x000070000228de30  rsp = 0x000070000228dc90  
 r8 = 0x0000200000000000   r9 = 0x0000000000000000  r10 = 0xffffffffffffffff  r11 = 0x00000fffffffffff  
r12 = 0x0000000000000004  r13 = 0x0000000000000000  r14 = 0x00001e0000451c38  r15 = 0x00001e0000451f1c  
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV mqtt_codec.c:2278 in property_dup
Thread T13 created by T0 here:
    #0 0x10111f31a in wrap_pthread_create+0x5a (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x4331a)
    #1 0x100ed162d in nni_plat_thr_init posix_thread.c:279
    #2 0x100eb253c in nni_thr_init thread.c:121
    #3 0x100eae184 in nni_taskq_init taskq.c:95
    #4 0x100eaf6d4 in nni_taskq_sys_init taskq.c:284
    #5 0x100e89bac in nni_init_helper init.c:35
    #6 0x100ed1ce9 in nni_plat_init posix_thread.c:422
    #7 0x100e89b8f in nni_init init.c:58
    #8 0x100f515bf in nni_proto_mqtt_open protocol.c:37
    #9 0x100f12752 in nng_nmq_tcp0_open nmq_mqtt.c:1231
    #10 0x100e2bfe7 in broker broker.c:764
    #11 0x100e30e4d in broker_start broker.c:1250
    #12 0x100dfba0c in main nanomq.c:221
    #13 0x7fff6b280cc8 in start+0x0 (libdyld.dylib:x86_64+0x1acc8)

==30416==ABORTING
[1]    30416 abort      ./nanomq/nanomq broker start
```

**Comment by JaylinYu** [comment]
my bad. sorry to break this.
fixed in #609
