### ISSUE TITLE
Memleak in work ctx allocation

### ISSUE THREAD

**Issue by JaylinYu** [emqx/nanomq#726]
this is only exsits in the most updated master branch caused by #714  (merge nanolib with nanonng)

**Comment by JaylinYu** [comment]
==214101==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 256 byte(s) in 32 object(s) allocated from:
    #0 0x7f3019863867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x55694cad1152 in nni_alloc ../nng/src/platform/posix/posix_alloc.c:20
    #2 0x55694caa0a9e in nng_alloc ../nng/src/nng.c:60
    #3 0x55694ca8c9bb in alloc_work ../nanomq/apps/broker.c:650
    #4 0x55694ca8cab3 in proto_work_init ../nanomq/apps/broker.c:664
    #5 0x55694ca8d1b3 in broker ../nanomq/apps/broker.c:841
    #6 0x55694ca901ae in broker_start ../nanomq/apps/broker.c:1382
    #7 0x55694ca6f530 in main ../nanomq/nanomq.c:214
    #8 0x7f301958cfcf in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

Direct leak of 16 byte(s) in 2 object(s) allocated from:
    #0 0x7f3019863867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x55694cad1152 in nni_alloc ../nng/src/platform/posix/posix_alloc.c:20
    #2 0x55694caa0a9e in nng_alloc ../nng/src/nng.c:60
    #3 0x55694ca8c9bb in alloc_work ../nanomq/apps/broker.c:650
    #4 0x55694ca8cab3 in proto_work_init ../nanomq/apps/broker.c:664
    #5 0x55694ca8d480 in broker ../nanomq/apps/broker.c:856
    #6 0x55694ca901ae in broker_start ../nanomq/apps/broker.c:1382
    #7 0x55694ca6f530 in main ../nanomq/nanomq.c:214
    #8 0x7f301958cfcf in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

SUMMARY: AddressSanitizer: 272 byte(s) leaked in 34 allocation(s).
