### ISSUE TITLE
Topic alias test failed

### ISSUE THREAD

**Issue by JaylinYu** [emqx/nanomq#918]
**Describe the bug**
CI failed when processing Topic alias

AddressSanitizer:DEADLYSIGNAL
=================================================================
AddressSanitizer:DEADLYSIGNAL
AddressSanitizer:DEADLYSIGNAL
==11907==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f4e46cc7482 bp 0x7f4e3d3f88d0 sp 0x7f4e3d3f8058 T7)
==11907==The signal is caused by a READ memory access.
==11907==Hint: address points to the zero page.
    #0 0x7f4e46cc7482  (/lib/x86_64-linux-gnu/libc.so.6+0x1b1482)
    #1 0x7f4e46d9fe2b in __interceptor_strchr ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:705
    #2 0x561f32781c85 in nng_mqtt_msg_set_publish_topic /home/runner/work/nanomq/nanomq/nng/src/supplemental/mqtt/mqtt_public.c:304
    #3 0x561f326d7c29 in bridge_publish_msg /home/runner/work/nanomq/nanomq/nanomq/bridge.c:68
    #4 0x561f32700652 in bridge_handler /home/runner/work/nanomq/nanomq/nanomq/apps/broker.c:173
    #5 0x561f32703e47 in server_cb /home/runner/work/nanomq/nanomq/nanomq/apps/broker.c:512
    #6 0x561f32736438 in nni_taskq_thread /home/runner/work/nanomq/nanomq/nng/src/core/taskq.c:50
    #7 0x561f327377f0 in nni_thr_wrap /home/runner/work/nanomq/nanomq/nng/src/core/thread.c:94
    #8 0x561f327409a5 in nni_plat_thr_main /home/runner/work/nanomq/nanomq/nng/src/platform/posix/posix_thread.c:266
    #9 0x7f4e46baab42  (/lib/x86_64-linux-gnu/libc.so.6+0x94b42)
    #10 0x7f4e46c3c9ff  (/lib/x86_64-linux-gnu/libc.so.6+0x1269ff)
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/lib/x86_64-linux-gnu/libc.so.6+0x1b1482) 
Thread T7 created by T0 here:
    #0 0x7f4e46dba685 in __interceptor_pthread_create ../../../../src/libsanitizer/asan/asan_interceptors.cpp:216
    #1 0x561f32740ad5 in nni_plat_thr_init /home/runner/work/nanomq/nanomq/nng/src/platform/posix/posix_thread.c:279
    #2 0x561f32737a9c in nni_thr_init /home/runner/work/nanomq/nanomq/nng/src/core/thread.c:121
    #3 0x561f3273675a in nni_taskq_init /home/runner/work/nanomq/nanomq/nng/src/core/taskq.c:95
    #4 0x561f327374ba in nni_taskq_sys_init /home/runner/work/nanomq/nanomq/nng/src/core/taskq.c:294
    #5 0x561f3272[13](https://github.com/emqx/nanomq/actions/runs/3520245674/jobs/5902165200#step:6:14)de in nni_init_helper /home/runner/work/nanomq/nanomq/nng/src/core/init.c:35
    #6 0x561f32740e7a in nni_plat_init /home/runner/work/nanomq/nanomq/nng/src/platform/posix/posix_thread.c:422
    #7 0x561f3272[14](https://github.com/emqx/nanomq/actions/runs/3520245674/jobs/5902165200#step:6:15)5f in nni_init /home/runner/work/nanomq/nanomq/nng/src/core/init.c:58
    #8 0x561f32780d58 in nng_mtx_alloc /home/runner/work/nanomq/nanomq/nng/src/supplemental/util/platform.c:93
    #9 0x561f326d70f6 in log_init /home/runner/work/nanomq/nanomq/nanomq/mqtt_api.c:223
    #10 0x561f3270a5e6 in broker_start /home/runner/work/nanomq/nanomq/nanomq/apps/broker.c:[15](https://github.com/emqx/nanomq/actions/runs/3520245674/jobs/5902165200#step:6:16)52
    #11 0x561f326d749f in main /home/runner/work/nanomq/nanomq/nanomq/nanomq.c:142
    #12 0x7f4e46b3fd8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
==11907==ABORTING
Sub client did not receive message * 10
mosquitto_sub -h 127.0.0.1 -p [18](https://github.com/emqx/nanomq/actions/runs/3520245674/jobs/5902165200#step:6:19)83 -t 'topic'
mosquitto_pub -h 1[27](https://github.com/emqx/nanomq/actions/runs/3520245674/jobs/5902165200#step:6:28).0.0.1 -p 1883 -t topic -V 5 -m message -D Publish topic-alias 10 -d --repeat 10
Topic alias test failed!
mqtt v5 test failed

**Comment by JaylinYu** [comment]
Closing this due to unable to reproduce
